# -*- coding: utf-8 -*-
"""faktorial_rekursif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13l7BNax1z2J5x9OqWGEelSWYJc9l47-E
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n - 1)

# Input dari pengguna
try:
    angka = int(input("Masukkan bilangan bulat positif: "))
    if angka < 0:
        print("Faktorial hanya dapat dihitung untuk bilangan positif atau nol.")
    else:
        hasil = faktorial(angka)
        print(f"Faktorial dari {angka} adalah {hasil}")
except ValueError:
    print("Input tidak valid. Harap masukkan bilangan bulat.")