# -*- coding: utf-8 -*-
"""hitung_diskon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfyQ7vPf2PNUqYQ4vQHO9Xh2_J5BDFTX
"""

# Program untuk menghitung total bayar setelah diskon
def hitung_total_bayar(total_belanja):
    if total_belanja > 500000:
        diskon = total_belanja * 0.10
        print(f"Anda mendapatkan diskon sebesar 10%: Rp{diskon}")
    else:
        diskon = 0
        print("Anda tidak mendapatkan diskon.")
    total_bayar = total_belanja - diskon
    print(f"Total yang harus dibayar: Rp{total_bayar}")
    return total_bayar

# Input dari pengguna
try:
    total_belanja = float(input("Masukkan total belanja Anda (Rp): "))
    hitung_total_bayar(total_belanja)
except ValueError:
    print("Input tidak valid. Harap masukkan angka.")