# -*- coding: utf-8 -*-
"""nilai_tertinggi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVQ3R2U1dUU7mkC7fIZY0h3D0M8yLdp4
"""

# Program untuk input nilai 5 siswa dan mencari nilai tertinggi

nilai_siswa = []

# Input nilai untuk 5 siswa
for i in range(5):
    while True:
        try:
            nilai = float(input(f"Masukkan nilai siswa ke-{i+1}: "))
            if 0 <= nilai <= 100:
                nilai_siswa.append(nilai)
                break
            else:
                print("Nilai harus antara 0 dan 100.")
        except ValueError:
            print("Input tidak valid. Masukkan angka.")

# Menentukan nilai tertinggi dan siswa keberapa
nilai_tertinggi = max(nilai_siswa)
siswa_tertinggi = nilai_siswa.index(nilai_tertinggi) + 1

print(f"\nNilai tertinggi adalah {nilai_tertinggi}, diperoleh oleh siswa ke-{siswa_tertinggi}.")