# -*- coding: utf-8 -*-
"""penentuan_kelulusan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1c85DABYoocwHEsUvaaQJEj759zWxsz
"""

# Program untuk menghitung rata-rata nilai dan menentukan status kelulusan
print("=== Program Penentuan Kelulusan ===")

# Input nilai dari tiga mata pelajaran
nilai1 = float(input("Masukkan nilai mata pelajaran ke-1: "))
nilai2 = float(input("Masukkan nilai mata pelajaran ke-2: "))
nilai3 = float(input("Masukkan nilai mata pelajaran ke-3: "))

# Menghitung rata-rata
rata_rata = (nilai1 + nilai2 + nilai3) / 3

# Menentukan status kelulusan
if rata_rata >= 75:
    status = "LULUS"
else:
    status = "TIDAK LULUS"

# Menampilkan hasil
print(f"Rata-rata nilai: {rata_rata:.2f}")
print(f"Status: {status}")