# -*- coding: utf-8 -*-
"""Program Kasir Sederhan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WuEAivSMadCLoxyWWek2wmUQsHYv9WI
"""

# Program Kasir Sederhana
print("=== Program Kasir Sederhana ===")

# Input harga tiga barang
harga1 = float(input("Masukkan harga barang ke-1: Rp "))
harga2 = float(input("Masukkan harga barang ke-2: Rp "))
harga3 = float(input("Masukkan harga barang ke-3: Rp "))

# Hitung total pembayaran
total = harga1 + harga2 + harga3

# Tampilkan total pembayaran
print(f"Total pembayaran: Rp {total:,.2f}")